Адаптивная сетка
htmlacademy-adaptive/2060893-mishka-27 pull request #5
Opened 2022-12-13 20:40 UTC by NickSmrnv

2022-12-23 21:50 UTC, vadimrahmanov requested changes

2022-12-23 21:50 UTC, vadimrahmanov commented on source/catalog.html
> +            <li class="main-nav__item extra-list__item">
Я правильно понял, что main-nav__list и extra-list разные блоки со своими элементами? если да, то не надо и тот и тот класс main-nav__item и extra-list__item, тут как бы просто extra-list__item напрашивается

2022-12-23 21:50 UTC, vadimrahmanov commented on source/form.html
> +          </ul>
тоже самое, что и сверху

2022-12-23 21:50 UTC, vadimrahmanov commented on source/index.html
> +          </ul>
Тоже самое, что сверху

2022-12-23 21:50 UTC, vadimrahmanov commented on source/index.html
> +            <a class="catalog-hero__button" type="button">
У ссылки не может быть type="button", а также должна быть сама ссылка (href). Это касается и нижних таких же ссылок.

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/catalog-hero.scss
> +  color: #ffffff;
Добавь цвета в переменные. Тут например $white можно

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/catalog-hero.scss
> +}
на странице каталога не нашёл элементов с такими классами

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/hero.scss
> +    padding-left: 50px;
Это никуда не годиться, просто отцентруй заголовок с помощью флексов

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/hero.scss
> +  }
Тоже самое, что сверху

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/main-footer.scss
> +  background-color: #f1f1f1;
в переменную

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/main-header.scss
> +  @media (min-width: $tablet-width) and (max-width: $desktop-width) {
Зачем тут max-width, если все равно снизу переписываешь?

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/main-nav.scss
> +  // @include visually-hidden;
коммент

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/main-nav.scss
> +  @media (min-width: $tablet-width) and (max-width: $desktop-width) {
зачем max-width?

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/main-nav.scss
> +  @media (min-width: $tablet-width), (min-width: $desktop-width) {
Что это такое? если у тебя min-width: $tablet, то всё, что от этой ширины включая десктоп будет использовать эти свойства.

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/reviews.scss
> +  }
Какие-то у тебя огромные значения. Внешние отступы должны быть не у wrappera, а у самой секции, так как между секциями нужны они. В принципе и с paddingami также можно поступить. И почему по бокам внешние отступы, если нужны внутренние?

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/blocks/user-list.scss
> +  @media (min-width: $tablet-width) and (max-width: $desktop-width) {
Зачем max-width? Если нужно что-то переписать, лучше сделать снизу @media (min-width: desktop). position: static идёт по-умолчанию и так.

2022-12-23 21:50 UTC, vadimrahmanov commented on source/sass/global/mixins.scss
>  }
Вместо этой катовасии и добавления каждой секции этой переменной можно просто сделать класс .container, но в твоём случае это всё лишнее, так как у тебя не должен быть сайт шире, чем ширина макета.

2022-12-25 15:58 UTC, NickSmrnv commented on source/sass/blocks/catalog-hero.scss
> +}
Это блок catalog-hero, он в index.html находится, под hero блоком сразу.

2022-12-25 16:19 UTC, NickSmrnv commented on source/sass/blocks/main-nav.scss
> +  @media (min-width: $tablet-width) and (max-width: $desktop-width) {
Чтобы на компьютерной версии не применялись эти свойства 
position: absolute;
    top: 70px;

2022-12-27 09:31 UTC, merged